name: Convert Draw.io to SVG
on:
  push:
    paths:
      - 'Docs/SerialCommunicatorDiagram.drawio'
  workflow_dispatch:
jobs:
  convert-drawio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk2.0-0 libgdk-pixbuf2.0-0 libxss1 libnotify4
        wget https://github.com/jgraph/drawio-desktop/releases/download/v25.0.2/drawio-amd64-25.0.2.deb
        sudo dpkg -i drawio-amd64-25.0.2.deb
        sudo apt-get install -f

    - name: "Remove installation files"
      run: |
        rm drawio-amd64-25.0.2.deb

    - name: Convert Draw.io to SVG using Xvfb
      run: |
        xvfb-run drawio --export --format svg --output Docs/SerialCommunicatorDiagram.svg Docs/SerialCommunicatorDiagram.drawio --background "#FFFFFF"

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add Docs/SerialCommunicatorDiagram.svg
        git commit -m "Auto-update SVG from Draw.io"
        git push
