name: Convert Draw.io to SVG
on:
  push:
    paths:
      - 'docs/SerialCommunicatorDiagram.drawio'
  workflow_dispatch:
jobs:
  convert-drawio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        wget https://github.com/jgraph/drawio-desktop/releases/download/v25.0.2/drawio-amd64-25.0.2.deb
        sudo dpkg -i drawio-amd64-25.0.2.deb
        sudo apt-get install -f

    - name: Convert Draw.io to SVG
      run: |
        drawio --export --format svg --output docs/SerialCommunicatorDiagram.svg docs/SerialCommunicatorDiagram.drawio

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/diagram.svg
        git commit -m "Auto-update SVG from Draw.io"
        git push
